[package]
name = "actix-app-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.1", features = ["derive", "cargo"] }
const-str = "0.6.2"
dotenvy = "0.15.7"
eyre = "0.6.8"

srv-api = { path = "../crates/srv-api" }
srv-storage = { path = "../crates/srv-storage", features = ["sync"] }
srv-tracing = { path = "../crates/srv-tracing" }

tokio = { workspace = true }

[features]
async = ["srv-storage/async"]

[build-dependencies]
vergen = { version = "8.0.0", features = ["build", "cargo", "git", "gitcl"] }
